name: test-and-lint

on: push

env:
  CI: true

jobs: 

  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm

      - run: make install
      # - run: make test
      - run: make lint

      - name: test-coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage